name       : lokalize
version    : 22.04.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/lokalize-22.04.0.tar.xz : 8083a6e746bb087a1164757d3a90e42b20fde905835e94463e5261cbe61ad9e4
homepage   : https://apps.kde.org/lokalize/
license    :
    - GPL-2.0-or-later
    - GFDL-1.2-or-later
component  : desktop.kde
summary    : Computer-Aided Translation System
description: |
    Lokalize is a computer-aided translation system that focuses on productivity and quality assurance. It is targeted for software translation and also integrates external conversion tools for freelance office document translation.
builddeps  :
    - pkgconfig(hunspell)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
