name       : lokalize
version    : 21.08.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/lokalize-21.08.2.tar.xz : 5556260920d9d8afd1a80bc35ffa385cf30e4ea5cd49d71fdd25819db543c405
homepage   : https://apps.kde.org/lokalize/
license    :
    - GPL-2.0-or-later
    - GFDL-1.2-or-later
component  : desktop.kde
summary    : Computer-Aided Translation System
description: |
    Lokalize is a computer-aided translation system that focuses on productivity and quality assurance. It is targeted for software translation and also integrates external conversion tools for freelance office document translation.
builddeps  :
    - pkgconfig(hunspell)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - knotifications-devel
    - kross-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
