name       : lokalize
version    : 20.08.3
release    : 24
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/lokalize-20.08.3.tar.xz : 28b76632612ac65a28b4de929dd4ea9565f307d983d1a3ec07f0401c9a464b45
homepage   : https://kde.org/applications/office/org.kde.lokalize
license    :
    - GPL-2.0-or-later
    - GFDL-1.2-or-later
component  : desktop.kde
summary    : Computer-Aided Translation System
description: |
    Lokalize is a computer-aided translation system that focuses on productivity and quality assurance. It is targeted for software translation and also integrates external conversion tools for freelance office document translation.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(hunspell)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - knotifications-devel
    - kross-devel
    - kwindowsystem-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |-
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
