name       : lokalize
version    : 21.04.2
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/lokalize-21.04.2.tar.xz : 1d5d61018995c2f86be0857fc50750e0b146df6859975a325277b9a3e797bfa9
homepage   : https://kde.org/applications/office/org.kde.lokalize
license    :
    - GPL-2.0-or-later
    - GFDL-1.2-or-later
component  : desktop.kde
summary    : Computer-Aided Translation System
description: |
    Lokalize is a computer-aided translation system that focuses on productivity and quality assurance. It is targeted for software translation and also integrates external conversion tools for freelance office document translation.
builddeps  :
    - pkgconfig(hunspell)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - knotifications-devel
    - kross-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
