name       : lokalize
version    : 23.04.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/lokalize-23.04.3.tar.xz : 1f71524b19d754d11f3057afda0cd02ea51a4b157a603bf92fcb13325b59f333
homepage   : https://apps.kde.org/lokalize/
license    :
    - GPL-2.0-or-later
    - GFDL-1.2-or-later
component  : desktop.kde
summary    : Computer-Aided Translation System
description: |
    Lokalize is a computer-aided translation system that focuses on productivity and quality assurance. It is targeted for software translation and also integrates external conversion tools for freelance office document translation.
builddeps  :
    - pkgconfig(hunspell)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
