name       : lokalize
version    : 21.08.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/lokalize-21.08.0.tar.xz : 03a1b47ad320bea47a6bbb9b80c13dd480400e7fcde07d4c8379f95295db9e57
homepage   : https://apps.kde.org/lokalize/
license    :
    - GPL-2.0-or-later
    - GFDL-1.2-or-later
component  : desktop.kde
summary    : Computer-Aided Translation System
description: |
    Lokalize is a computer-aided translation system that focuses on productivity and quality assurance. It is targeted for software translation and also integrates external conversion tools for freelance office document translation.
builddeps  :
    - pkgconfig(hunspell)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - knotifications-devel
    - kross-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
