name       : lokalize
version    : 19.12.3
release    : 15
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/lokalize-19.12.3.tar.xz : 8015c994e974fd51c1c7f5903a005bbbc25f094656bdd44cd5e8675cd69cea92
homepage   : https://kde.org/applications/office/org.kde.lokalize
license    :
    - GPL-2.0-or-later
    - GFDL-1.2-or-later
component  : desktop.kde
summary    : Computer-Aided Translation System
description: |
    Lokalize is a computer-aided translation system that focuses on productivity and quality assurance. It is targeted for software translation and also integrates external conversion tools for freelance office document translation.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(hunspell)
    - extra-cmake-modules
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - knotifications-devel
    - kross-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
