name       : lokalize
version    : 19.04.0
release    : 3
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/lokalize-19.04.0.tar.xz : e2e8cd6f9bb0e59ffd4b88e5513b757df3b63892ce90e7000c872e896ef74266
license    :
    - GPL-2.0-or-later
    - GFDL-1.2-or-later
component  : desktop.kde
summary    : Computer-Aided Translation System
description: |
    Lokalize is a computer-aided translation system that focuses on productivity and quality assurance. It is targeted for software translation and also integrates external conversion tools for freelance office document translation.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(hunspell)
    - extra-cmake-modules
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kross-devel
    - kxmlgui-devel
    - sonnet-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
