name       : lokalize
version    : 23.04.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/lokalize-23.04.0.tar.xz : fb6501c258f2132dfa9c3fe17b4f75eb3ab3b363746dd22d9408504f2ac90707
homepage   : https://apps.kde.org/lokalize/
license    :
    - GPL-2.0-or-later
    - GFDL-1.2-or-later
component  : desktop.kde
summary    : Computer-Aided Translation System
description: |
    Lokalize is a computer-aided translation system that focuses on productivity and quality assurance. It is targeted for software translation and also integrates external conversion tools for freelance office document translation.
builddeps  :
    - pkgconfig(hunspell)
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kio-devel
    - knotifications-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
